# Generated by Django 3.2 on 2022-07-12 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InrRangeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inr_type', models.CharField(choices=[('INR 2-3', '2-3 PROTOCOL'), ('INR 2.5-3.5', '2.5-3.5 PROTOCOL')], default='INR 2-3', max_length=20)),
                ('inr_range', models.CharField(default='0', max_length=50)),
                ('remedy', models.CharField(default='EXtra Dose and or increase weekly dose by 10-20%', max_length=50)),
                ('return_to_clinc', models.CharField(default='2 to 3 weeks', max_length=50)),
            ],
            options={
                'db_table': 'inrrange_profile',
            },
        ),
        migrations.CreateModel(
            name='PaitentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Full name', max_length=50)),
                ('age', models.PositiveIntegerField(default=20)),
                ('residence', models.CharField(default='Kenya', max_length=50)),
                ('email', models.EmailField(default='patient@gmail.com', max_length=255, unique=True)),
                ('phone_number', models.CharField(default='0723467890', max_length=10, unique=True)),
                ('bp', models.PositiveIntegerField(default=21)),
                ('temparature', models.PositiveIntegerField(default=37)),
                ('height', models.CharField(default='1.75m', max_length=50)),
                ('weight', models.CharField(default='60 kgs', max_length=50)),
                ('inr_range', models.PositiveIntegerField(default=2.4)),
                ('currency_dose', models.CharField(default='5 mg', max_length=50)),
                ('diagnosis', models.CharField(default='Continue with the previous dose of ...  RTC 2 to 4 Weeks', max_length=50)),
            ],
            options={
                'db_table': 'paitent_profile',
            },
        ),
        migrations.CreateModel(
            name='ReceptionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(default='firstname', max_length=50)),
                ('last_name', models.CharField(default='lastname', max_length=50)),
                ('phone_number', models.CharField(default='12345678', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reception_profile',
            },
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(default='firstname', max_length=50)),
                ('last_name', models.CharField(default='lastname', max_length=50)),
                ('phone_number', models.CharField(default='12345678', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nurse_profile',
            },
        ),
        migrations.CreateModel(
            name='LabtechProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(default='firstname', max_length=50)),
                ('last_name', models.CharField(default='lastname', max_length=50)),
                ('phone_number', models.CharField(default='12345678', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labtech_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'labtech_profile',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(default='firstname', max_length=50)),
                ('last_name', models.CharField(default='lastname', max_length=50)),
                ('phone_number', models.CharField(default='12345678', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_profile',
            },
        ),
    ]
