# Generated by Django 3.1.2 on 2022-07-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='phone_number',
        ),
    ]
