# Generated by Django 3.1.2 on 2022-07-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20220706_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtechprofile',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='nurseprofile',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='receptionprofile',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='labtechprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='labtechprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='labtechprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='labtechprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='receptionprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='receptionprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='receptionprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='receptionprofile',
            name='phone_number',
        ),
    ]
