# Generated by Django 3.2 on 2022-07-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20220712_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='username',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='labtechprofile',
            old_name='username',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='nurseprofile',
            old_name='username',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='receptionprofile',
            old_name='username',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='labtechprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='labtechprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='receptionprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='receptionprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='inrrangeprofile',
            name='remedy',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='inrrangeprofile',
            name='return_to_clinc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='labtechprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='labtechprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='bp',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='height',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='inr_range',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='residence',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='temparature',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='weight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='receptionprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='receptionprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
