# Generated by Django 3.2 on 2022-07-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20220712_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inrrangeprofile',
            name='inr_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
