# Generated by Django 3.2 on 2022-07-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20220707_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='first_name',
            field=models.CharField(default='firstname', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_name',
            field=models.CharField(default='lastname', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(default='12345678', max_length=10),
        ),
        migrations.AddField(
            model_name='labtechprofile',
            name='first_name',
            field=models.CharField(default='firstname', max_length=50),
        ),
        migrations.AddField(
            model_name='labtechprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='labtechprofile',
            name='last_name',
            field=models.CharField(default='lastname', max_length=50),
        ),
        migrations.AddField(
            model_name='labtechprofile',
            name='phone_number',
            field=models.CharField(default='12345678', max_length=10),
        ),
        migrations.AddField(
            model_name='receptionprofile',
            name='first_name',
            field=models.CharField(default='firstname', max_length=50),
        ),
        migrations.AddField(
            model_name='receptionprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='receptionprofile',
            name='last_name',
            field=models.CharField(default='lastname', max_length=50),
        ),
        migrations.AddField(
            model_name='receptionprofile',
            name='phone_number',
            field=models.CharField(default='12345678', max_length=10),
        ),
    ]
