# Generated by Django 3.2 on 2022-07-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_inrrangeprofile_inr_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inrrangeprofile',
            name='inr_range',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
