# Generated by Django 3.2 on 2022-07-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_alter_inrrangeprofile_inr_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inrprotocolprofile',
            old_name='inr_protocal',
            new_name='inr_protocol',
        ),
    ]
