# Generated by Django 3.2 on 2022-07-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20220708_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paitentprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
