# Generated by Django 3.2 on 2022-07-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_rename_inr_protocal_inrprotocolprofile_inr_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inrrangeprofile',
            name='inr_protocol',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='InrProtocolProfile',
        ),
    ]
