# Generated by Django 3.2 on 2022-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_paitentprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paitentprofile',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='full_name',
            field=models.CharField(default='Full name', max_length=50),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='phone_number',
            field=models.CharField(default='0723467890', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='residence',
            field=models.CharField(default='Kenya', max_length=50),
        ),
    ]
