# Generated by Django 3.2 on 2022-07-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20220712_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='paitentprofile',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
