# Generated by Django 3.2 on 2022-07-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_paitentprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paitentprofile',
            name='diagnosis',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paitentprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
