# Generated by Django 4.0.5 on 2022-07-02 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appwarfarin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='INR_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INR_Range_name', models.CharField(max_length=100)),
                ('INR_Range_min', models.IntegerField()),
                ('INR_Range_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=100)),
                ('Patient_age', models.IntegerField()),
                ('Patient_Residence', models.CharField(max_length=100)),
                ('Patient_phone', models.IntegerField()),
                ('Patient_email', models.EmailField(max_length=100)),
                ('Patient_Bp', models.IntegerField()),
                ('Patient_weight', models.IntegerField()),
                ('Patient_height', models.IntegerField()),
                ('Patient_temperature', models.IntegerField()),
                ('Patient_Inr', models.IntegerField()),
                ('Patient_Diagnosis', models.CharField(max_length=100)),
            ],
        ),
    ]
