# Generated by Django 3.1.2 on 2022-07-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_nurse',
            field=models.BooleanField(default=False),
        ),
    ]
